# Generated by Django 2.2.7 on 2020-04-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_writing'),
    ]

    operations = [
        migrations.AddField(
            model_name='writing',
            name='quotefrom',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='writing',
            name='source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
