# Generated by Django 2.2.7 on 2020-04-21 00:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_auto_20200416_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Excerpt',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
