# Generated by Django 2.2.7 on 2020-04-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0005_auto_20200421_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Excerpt',
            field=models.TextField(blank=True, null=True),
        ),
    ]
