# Generated by Django 2.2.7 on 2020-04-22 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0006_auto_20200421_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Excerpt',
        ),
    ]
